# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: checkout
#       uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build -t codemaivanngu/search-api:latest .

#       # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#     - name: pushing image to docker hub
#       run: |
#         docker login -u codemaivanngu -p ${{secrets.DOCKER_HUB_TOKEN}}
#         docker push codemaivanngu/search-api:latest

name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker images
        run: |
          docker build \
            --tag codemaivanngu/search-api:latest \
            --tag ghcr.io/${{ github.repository_owner }}/search-api:latest \
            .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: codemaivanngu
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push codemaivanngu/search-api:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/search-api:latest
